ai-recruit-board/urls.py
from django.urls import path, include

from django.contrib import admin
from apps.core.views import frontpage, signup
from django.contrib.auth import views
from apps.job.views import job_detail, add_job
from apps.userprofile.views import dashboard

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", frontpage, name="frontpage"),
    path("signup/", signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path("admin/", admin.site.urls),
    path('jobs/', include('apps.job.urls')),
    path('dashboard/', include('apps.userprofile.urls')),

]

gettingstarted/urls.py
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

import MainAPP.views

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", MainAPP.views.index, name="index"),
    path("portfolio/", MainAPP.views.portfolio, name="portfolio"),
    path("db/", MainAPP.views.db, name="db"),
    path("admin/", admin.site.urls),
]

apps/job/models.py
from django.contrib.auth.models import User
from django.db import models
from multiselectfield import MultiSelectField

class Job(models.Model):
    SIZE_1_9 = 'size_1-9'
    SIZE_10_49 = 'size_10-49'
    SIZE_50_99 = 'size_50-99'
    SIZE_100 = 'size_100'

    CHOICES_SIZE = (
        (SIZE_1_9, '1-9'),
        (SIZE_10_49, '10-49'),
        (SIZE_50_99, '50-99'),
        (SIZE_100, '100+'),
    )

    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'
    skills = (
        ('Python','Python'),
        ('AWS', 'AWS'),
        ('Azure', 'Azure'),
    )
    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (EMPLOYED, 'Employed'),
        (ARCHIVED, 'Archived')
    )

    title = models.CharField(max_length=255)
    short_description = models.TextField()
    long_description = models.TextField(blank=True, null=True)
    skill_set = MultiSelectField(choices=skills, default='none')
    company_name = models.CharField(max_length=255,blank=True, null=True)
    company_address = models.CharField(max_length=255, blank=True, null=True)
    company_zipcode = models.CharField(max_length=255, blank=True, null=True)
    company_place = models.CharField(max_length=255, blank=True, null=True)
    company_country = models.CharField(max_length=255, blank=True, null=True)
    company_size = models.CharField(max_length=20, choices=CHOICES_SIZE, default=SIZE_1_9, blank=True, null=True)


    created_by = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ACTIVE)

    def __str__(self):

        return self.title

class Application(models.Model):
    job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()

    created_by = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.job.models import Application
from multiselectfield import MultiSelectField

# Create your models here.

class Userprofile(models.Model):
    skills = (
        ('Python','Python'),
        ('AWS', 'AWS'),
        ('Azure', 'Azure'),
        ('None', 'None')
    )

    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    is_employer = models.BooleanField(default=False)
    skill_set = MultiSelectField(choices = skills, default='none')

    def __str__(self):
        return str(self.user)



User.userprofile = property(lambda u:Userprofile.objects.get_or_create(user=u)[0])

class ConversationMessage(models.Model):
    application = models.ForeignKey(Application, related_name='conversationmessages', on_delete=models.CASCADE)
    content = models.TextField()

    created_by = models.ForeignKey(User, related_name='conversationmessages', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.created_at

    class Meta:
        ordering = ['created_at']

apps/userprofile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import ConversationMessage
from  apps.job.models import Application, Job

# Create your views here.
@login_required
def dashboard(request):
    return render(request, 'userprofile/dashboard.html', {'userprofile':request.user.userprofile})


@login_required
def view_application(request, application_id):
    if request.user.userprofile.is_employer:
        application = get_object_or_404(Application, pk=application_id, job__created_by=request.user)
    else:
        application = get_object_or_404(Application, pk=application_id,created_by=request.user)

    if request.method == 'POST':
        content = request.POST.get('content')

        if content:
            conversationmessage = ConversationMessage.object.create(application=application, created_by =request.user)

            return redirect('view_application', application_id=application_id)

    return render(request, 'userprofile/view_application.html', {'application': application})


@login_required
def view_dashboard_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id, created_by=request.user)

    return render(request, 'userprofile/view_dashboard_job.html', {'job': job})

templates/userprofile/dashboard.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">Dashboard</h1>

    {% if userprofile.is_employer %}
        <h2 class="subtitle">Jobs</h2>

        <a href="{% url 'add_job' %}" class="button is-success">Add job</a>

        {% for job in request.user.jobs.all %}
            <div class="job">
                <a href="{% url 'view_dashboard_job' job.id %}">{{ job.title }} ({{ job.get_status_display }})</a>
            </div>
        {% empty %}
            <p>You don't have any jobs yet...</p>
        {% endfor %}
    {% else %}
        <h2 class="subtitle">Applications</h2>

        {% for application in request.user.applications.all %}
            <div class="application">
                <a href="{% url 'view_application' application.id %}">{{ application.job.title }}</a>
            </div>
        {% empty %}
            <p>You haven't applied for any jobs yet...</p>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/userprofile/view_application.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">View application</h1>

    <h2 class="subtitle">{{ application.job.title }}</h2>

    <small>Date added: {{ application.created_at }}</small>

    <p><strong>Content: </strong><br>{{ application.content }}</p>
    <p><strong>Experience: </strong><br>{{ application.experience }}</p>

    <hr>

    <h2 class="subtitle">Conversation</h2>

    {% for message in application.conversationmessages.all %}
        <div class="notification">
            <b>{{ message.created_by.username }} - {{ message.created_at|timesince }} ago</b><br>

            {{ message.content }}
        </div>
    {% empty %}
        <p>No messages yet...</p>

        <hr>
    {% endfor %}
    
    <form method="post" action=".">
        {% csrf_token %}

        <div class="field">
            <div class="control">
                <textarea class="textarea" placeholder="Your message" name="content" id="id_content"></textarea>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Send</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/userprofile/view_dashboard_job.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">View job - {{ job.title }}</h1>

    <a href="{% url 'edit_job' job.id %}" class="button is-success mb-4">Edit</a>

    <p class="is-size-4">{{ job.short_description }}</p>

    <p>{{ job.long_description }}</p>

    <b>Company name: </b>{{ job.company_name}}<br>
    <b>Company address: </b>{{ job.company_address}}<br>
    <b>Company zipcode: </b>{{ job.company_zipcode}}<br>
    <b>Company place: </b>{{ job.company_place}}<br>
    <b>Company country: </b>{{ job.company_country}}<br>
    <b>Company size: </b>{{ job.get_company_size_display }}<br>

    {% for application in job.applications.all %}
        <a href="{% url 'view_application' application.id %}">{{ application.created_by.username }}</a>
    {% endfor %}
{% endblock %}