ai-recruit-board/urls.py
from django.urls import path, include

from django.contrib import admin
from apps.core.views import frontpage, signup
from django.contrib.auth import views
from apps.job.views import job_detail, add_job
from apps.userprofile.views import dashboard

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", frontpage, name="frontpage"),
    path("signup/", signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path("admin/", admin.site.urls),
    path('jobs/', include('apps.job.urls')),
    path('dashboard/', include('apps.userprofile.urls')),

]

apps/job/urls.py
from django.urls import path, include

from .views import job_detail, add_job, apply_for_job, edit_job

urlpatterns = [
    path('add/', add_job, name='add_job'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/edit/', edit_job, name='edit_job'),
    path('<int:job_id>/apply_for_job', apply_for_job, name='apply_for_job'),
]

gettingstarted/urls.py
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

import MainAPP.views

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", MainAPP.views.index, name="index"),
    path("portfolio/", MainAPP.views.portfolio, name="portfolio"),
    path("db/", MainAPP.views.db, name="db"),
    path("admin/", admin.site.urls),
]

apps/job/models.py
from django.contrib.auth.models import User
from django.db import models
from multiselectfield import MultiSelectField

class Job(models.Model):
    SIZE_1_9 = 'size_1-9'
    SIZE_10_49 = 'size_10-49'
    SIZE_50_99 = 'size_50-99'
    SIZE_100 = 'size_100'

    CHOICES_SIZE = (
        (SIZE_1_9, '1-9'),
        (SIZE_10_49, '10-49'),
        (SIZE_50_99, '50-99'),
        (SIZE_100, '100+'),
    )

    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'
    skills = (
        ('Python','Python'),
        ('AWS', 'AWS'),
        ('Azure', 'Azure'),
    )
    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (EMPLOYED, 'Employed'),
        (ARCHIVED, 'Archived')
    )

    title = models.CharField(max_length=255)
    short_description = models.TextField()
    long_description = models.TextField(blank=True, null=True)
    skill_set = MultiSelectField(choices=skills, default='none')
    company_name = models.CharField(max_length=255,blank=True, null=True)
    company_address = models.CharField(max_length=255, blank=True, null=True)
    company_zipcode = models.CharField(max_length=255, blank=True, null=True)
    company_place = models.CharField(max_length=255, blank=True, null=True)
    company_country = models.CharField(max_length=255, blank=True, null=True)
    company_size = models.CharField(max_length=20, choices=CHOICES_SIZE, default=SIZE_1_9, blank=True, null=True)


    created_by = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ACTIVE)

    def __str__(self):

        return self.title

class Application(models.Model):
    job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()

    created_by = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

apps/job/forms.py
from django import forms

from .models import Job, Application

class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'short_description', 'long_description', 'company_name', 'company_address', 'company_zipcode', 'company_place', 'company_country', 'company_size']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['content', 'experience']

apps/job/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Job
from .forms import AddJobForm, ApplicationForm


def job_detail(request, job_id):
    job =Job.objects.get(pk=job_id)

    return render(request, 'job/job_detail.html', {'job': job})

@login_required
def apply_for_job(request, job_id):
    job = Job.objects.get(pk=job_id)

    if request.method == 'POST':
        form = ApplicationForm(request.POST)

        if form.is_valid():
            application = form.save(commit=False)
            application.job = job
            application.created_by = request.user
            application.save()

            return redirect('dashboard')

    else:
        form = ApplicationForm()

    return  render(request, 'job/apply_for_job.html',{'form': form, 'job':job})

@login_required
def add_job(request):
    if request.method == 'POST':
        form = AddJobForm(request.POST)

        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = request.user
            job.save()

            return redirect('dashboard')
    else:
        form = AddJobForm()

    return render(request, 'job/add_job.html', {'form': form})


@login_required
def edit_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id, created_by=request.user)

    if request.method == 'POST':
        form = AddJobForm(request.POST, instance=job)

        if form.is_valid():
            job = form.save(commit=False)
            job.status = request.POST.get('status')
            job.save()

            return redirect('dashboard')
    else:
        form = AddJobForm(instance=job)

    return render(request, 'job/edit_job.html', {'form': form, 'job': job})

templates/job/add_job.html
{% extends 'core/base.html' %}

{% block content %}

    <h1 class="title">Add job</h1>


    <form method="post" action=".">
        {% csrf_token %}

        {% if form.errors %}
            {% for error in form.errors %}
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="field">
            <label> Title</label>

            <div class="control">
                <input class="input" type="text" name="title" id="id_title">
            </div>
        </div>
        <div class="field">
            <label> company name</label>

            <div class="control">
                <input class="input" type="text" name="company name" id="company_name">
            </div>
        </div>
        <div class="field">
            <label> company address</label>

            <div class="control">
                <input class="input" type="text" name="company address" id="company_address">
            </div>
        </div>

        <div class="field">
            <label> Short description</label>

            <div class="control">
                <textarea type="textarea" name="short_description" id="id_short_description"></textarea>
            </div>
        </div>
        <div class="field">
            <label> Long description</label>

            <div class="control">
                <textarea type="textarea" name="long_description" id="id_long_description"></textarea>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>
    </form>


{% endblock %}

templates/job/apply_for_job.html
{% extends 'core/base.html' %}

{% block content %}

    <h1 class="title">Apply for job - {{job.title}}</h1>


    <form method="post" action=".">
        {% csrf_token %}

        {% if form.errors %}
            {% for error in form.errors %}
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="field">
            <label>Content</label>

            <div class="control">
                <textarea type="textarea" name="content" id="id_content"></textarea>
            </div>
        </div>
        <div class="field">
            <label> experience</label>

            <div class="control">
                <textarea type="textarea" name="experience" id="id_experience"></textarea>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>
    </form>


{% endblock %}

templates/job/edit_job.html
{% extends 'core/base.html' %}

{% block content %}
    <div id="edit-job-app">
        <h1 class="title">Edit job</h1>

        <form v-on:submit="validateForm" method="post" action=".">
            {% csrf_token %}

            {% if form.errors %}
                {% for error in form.errors %}
                    <div class="notification is-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input class="input" type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Short description</label>

                <div class="control">
                    <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Long description</label>

                <div class="control">
                    <textarea class="textarea" name="long_description" id="id_long_description">{% if job.long_description %}{{ job.long_description }}{% endif %}</textarea>
                </div>
            </div>

            <div class="field">
                <label>Company name</label>

                <div class="control">
                    <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
                </div>
            </div>

            <div class="field">
                <label>Company address</label>

                <div class="control">
                    <input class="input" type="text" name="company_address" id="id_company_address" value="{% if job.company_address %}{{ job.company_address }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company zipcode</label>

                <div class="control">
                    <input class="input" type="text" name="company_zipcode" id="id_company_zipcode" value="{% if job.company_zipcode %}{{ job.company_zipcode }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company place</label>

                <div class="control">
                    <input class="input" type="text" name="company_place" id="id_company_place" value="{% if job.company_place %}{{ job.company_place }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company country</label>

                <div class="control">
                    <input class="input" type="text" name="company_country" id="id_company_country" value="{% if job.company_country %}{{ job.company_country }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company size</label>

                <div class="control">
                    <div class="select">
                        <select name="company_size" v-model="company_size">
                            <option value="">Choose size</option>
                            <option value="size_1-9">1-9</option>
                            <option value="size_10-49">10-49</option>
                            <option value="size_50-99">50-99</option>
                            <option value="size_100">100+</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>Status</label>

                <div class="control">
                    <div class="select">
                        <select name="status">
                            <option value="active"{% if job.status == 'active' %} selected{% endif %}>Active</option>
                            <option value="employed"{% if job.status == 'employed' %} selected{% endif %}>Employed</option>
                            <option value="archived"{% if job.status == 'archived' %} selected{% endif %}>Archived</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Save changes</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const EditJobApp = {
        data() {
            return {
                title: '{{ job.title }}',
                company_name: '{{ job.company_name }}',
                short_description: '{{ job.short_description }}',
                company_size: '{{ job.company_size }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('The company name field is missing!')
                }

                if (this.company_size === '') {
                    this.errors.push('The company size is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(EditJobApp).mount('#edit-job-app');
</script>
{% endblock %}

templates/job/job_detail.html
{% extends 'core/base.html'%}

{% block content %}
    <h1 class="title">{{ job.title }}</h1>

    <p> {{ job.company_name }}</p>
    <p> {{ job.company_address }}</p>
    <p> {{ job.company_zipcode }}</p>
    <p> {{ job.company_place }}</p>
    <p class="is-size-4"> {{ job.short_description }}</p>

    <p> {{ job.long_description }}</p>

    {% if job.status == 'active' %}
        <a href="{% url 'apply_for_job' job.id %}" class="button is-success">Apply for job</a>
    {% else %}
        <p>This job is not available anymore!</p>
    {% endif %}
{% endblock %}